App:
  Port: 8081

Database:
  Host: "127.00.0.1"
  Port: 5432
  Environment:
  Username: "postgres"
  Password: "yagami2909"
  DBName: "timesheet-be"

Files:
  Path: "./files"

Jwt:
  Secret: "q1w2e3r4t5y6"